Python library is collection of pre written codes to perform complex task quickly. It is used to save time,efforts,and code reuseability and simplify the complex tasks.

The array is a type which only consists one data type as all numeric means all element should be integer or float and list consists mixed data types.and numpy array consists of advanced numerical operations and list consits of basic numerical operations.Array uses less  memory as compared to list.

In [2]:
import numpy as np
x=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print('shape:',np.shape(x))
print('size:',np.size(x))
print('dimension:',np.ndim(x))

shape: (3, 4)
size: 12
dimension: 2


In [3]:
x[0]

array([1, 2, 3, 4])

In [4]:
element=x[2,3]
print("The element of 3rd row and 4thn colum is:",element)

The element of 3rd row and 4thn colum is: 12


In [5]:
prime_elements=x[1::2]
print("The index element with odd number are :",prime_elements)

The index element with odd number are : [[5 6 7 8]]


In [6]:
array=np.random.rand(3,3)
print("The random metrics of 3X3 between 1,0 is:",array)

The random metrics of 3X3 between 1,0 is: [[0.44817403 0.82693796 0.30207552]
 [0.29044153 0.26155431 0.31865298]
 [0.06418242 0.71048844 0.00971832]]


The np.random.rand() Generates the value from uniform distribution in a range and np.random.randn() Generates the value from normal distribution.

In [18]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
new_arr = np.expand_dims(arr, axis=0)
print(new_arr)
print("Shape:", new_arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Shape: (1, 3, 4)


In [20]:
transposed_array=np.transpose(arr)
print("The trandsposed array is:",transposed_array)

The trandsposed array is: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [25]:
a=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
b=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [27]:
indexwise_multiply=np.multiply(a,b)
print(indexwise_multiply)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [28]:
print("Matrix multiplication is:",a*b)

Matrix multiplication is: [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [30]:
print("Matrix addition is:",a+b)

Matrix addition is: [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [31]:
print("Matrix subtraction is:",b-a)

Matrix subtraction is: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [35]:
print("Matrix division is:",b/a)

Matrix division is: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In Python numpy the np.ndarray.byteswap() function is used for byte order swap of an array.

The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix.

np.reshape() is used to change the dimension and reshape the array or matrix in python and it is used by bassing the matrix as np.reshape(x):


Broadcasting in numpy is refered to as strong mechanisam to solve the complex claculation of mathematics. And it also allows to perform the arithematic operations on array with different shapes.